import Modeler from './Modeler';
import DCRModeler from "modeler";

import emptyBoardXML from '../resources/emptyBoard';
import { useEffect, useRef, useState } from 'react';

import { saveAs } from 'file-saver';
import { StateEnum, StateProps } from '../App';
import FileUpload from '../utilComponents/FileUpload';
import ModalMenu, { ModalMenuElement } from '../utilComponents/ModalMenu';

import { BiAnalyse, BiHome, BiLeftArrowCircle, BiPlus, BiSave, BiSolidDashboard } from 'react-icons/bi';

import Examples from './Examples';
import { toast } from 'react-toastify';
import TopRightIcons from '../utilComponents/TopRightIcons';
import Toggle from '../utilComponents/Toggle';
import DropDown from '../utilComponents/DropDown';
import { isSettingsVal } from '../types';
import { useHotkeys } from 'react-hotkeys-hook';
import FullScreenIcon from '../utilComponents/FullScreenIcon';
import StyledFileUpload from '../utilComponents/StyledFileUpload';
import MenuElement from '../utilComponents/MenuElement';
import Label from '../utilComponents/Label';
import Loading from '../utilComponents/Loading';
import { DCRGraph, layoutGraph, moddleToDCR, nestDCR, Nestings } from 'dcr-engine';
import GraphNameInput from '../utilComponents/GraphNameInput';
import { convertBPMNToDCRWithPyodide } from './pyodideBPMNConverter';

const initGraphName = "DCR-JS Graph"

// Helper function to process and format error messages from Python/Pyodide
function handleConversionError(dcrXmlOrError: string): { title: string; message: string } {
    let title = "BPMN to DCR Conversion Failed"; // Default fallback title
    let message = dcrXmlOrError;
    let prefixStripped = false;

    const knownPrefixes: Array<{prefix: string, generalTitle: string, stripMessageStart?: string}> = [
        { prefix: "PYTHON_PRECONDITION_ERROR:", generalTitle: "BPMN Precondition Checks Failed", stripMessageStart: "BPMN precondition checks failed:" },
        { prefix: "PYTHON_LOAD_ERROR:", generalTitle: "BPMN File Load Error" },
        { prefix: "PYTHON_LOAD_ERROR_UNCAUGHT:", generalTitle: "BPMN File Load Error (Uncaught)" },
        { prefix: "PYTHON_PAIR_GATEWAYS_ERROR:", generalTitle: "Gateway Pairing Error" },
        { prefix: "PYTHON_PRECHECK_ERROR_UNCAUGHT:", generalTitle: "Precondition Check Error (Uncaught)" },
        { prefix: "PYTHON_TRANSLATOR_ERROR:", generalTitle: "BPMN Translation Error" },
        { prefix: "PYTHON_TRANSLATION_RULES_ERROR:", generalTitle: "Translation Rule Application Error" },
        { prefix: "PYTHON_EXPORT_DCR_ERROR:", generalTitle: "DCR Export Error" },
        { prefix: "PYTHON_READ_DCR_OUTPUT_ERROR:", generalTitle: "Error Reading DCR Output" },
        { prefix: "PYTHON_WRITE_TEMP_BPMN_ERROR:", generalTitle: "Temporary File Error" },
        { prefix: "PYTHON_CONVERTER_UNHANDLED_ERROR:", generalTitle: "Unhandled Converter Error (Python)" }, // From Pyodide wrapper in pyodideBPMNConverter.ts
        { prefix: "PYODIDE_PYTHON_RETURN_UNEXPECTED_TYPE:", generalTitle: "Pyodide Interface Error" }, // From pyodideBPMNConverter.ts
        { prefix: "PYTHON_ERROR_FROM_PYODIDE:", generalTitle: "Python Execution Error" }, // From pyodideBPMNConverter.ts
        { prefix: "PYODIDE_SETUP_ERROR:", generalTitle: "Pyodide Setup Error" }, // From pyodideBPMNConverter.ts
        { prefix: "PYODIDE_SETUP_UNKNOWN_ERROR:", generalTitle: "Pyodide Setup Error (Unknown)" }, // From pyodideBPMNConverter.ts
    ];

    for (const entry of knownPrefixes) {
        if (dcrXmlOrError.startsWith(entry.prefix)) {
            title = entry.generalTitle;
            message = dcrXmlOrError.substring(entry.prefix.length).trim();
            if (entry.stripMessageStart && message.toLowerCase().startsWith(entry.stripMessageStart.toLowerCase())) {
                message = message.substring(entry.stripMessageStart.length).trim();
            }
            prefixStripped = true;
            break;
        }
    }

    if (!prefixStripped && (dcrXmlOrError.startsWith("PYTHON_") || dcrXmlOrError.startsWith("PYODIDE_"))) {
        // Generic handler for other PYTHON_ or PYODIDE_ errors not explicitly listed above
        const colonIndex = dcrXmlOrError.indexOf(':');
        if (colonIndex > -1) {
            let autoGeneratedTitle = dcrXmlOrError.substring(0, colonIndex)
                .replace(/_/g, ' ')
                .replace("PYTHON ", "")
                .replace("PYODIDE ", "")
                .toLowerCase();
            autoGeneratedTitle = autoGeneratedTitle.split(' ').map(s => s.charAt(0).toUpperCase() + s.substring(1)).join(' ').trim();

            if (autoGeneratedTitle && autoGeneratedTitle.toUpperCase() !== "ERROR") {
                title = autoGeneratedTitle;
            } else {
                title = "Conversion System Error"; // Fallback if auto-title is too generic
            }
            message = dcrXmlOrError.substring(colonIndex + 1).trim();
        } else {
            // If no colon, message is the whole string but we know it's a system error.
            title = "Conversion System Error";
            message = dcrXmlOrError; // Keep full message if structure is unexpected
        }
    }
    
    // Ensure message is not empty, if it became empty after stripping
    if (!message.trim() && dcrXmlOrError !== message) { // only if message was changed
        message = "Details provided in the error code or refer to console.";
    }


    return { title, message };
}


const ModelerState = ({ setState, savedGraphs, setSavedGraphs, lastSavedGraph }: StateProps) => {
  const [examplesOpen, setExamplesOpen] = useState(false);
  const [examplesData, setExamplesData] = useState<Array<string>>([]);

  const [menuOpen, setMenuOpen] = useState(false);

  const [loading, setLoading] = useState(false);

  const modelerRef = useRef<DCRModeler | null>(null);

  const lastGraph = lastSavedGraph.current;

  const [graphName, setGraphName] = useState<string>(lastGraph ? lastGraph : initGraphName);
  const [graphId, setGraphId] = useState<string>("");

  const saveGraph = () => {
    let shouldSave = true;
    if (savedGraphs[graphName] && graphName !== graphId) shouldSave = confirm(`This will overwrite the previously saved graph '${graphName}'. Are you sure you wish to continue?`);

    if (shouldSave) {
      setLoading(true);
      modelerRef.current?.saveXML({ format: false }).then(data => {
        const newSavedGraphs = { ...savedGraphs };
        newSavedGraphs[graphName] = data.xml;
        setGraphId(graphName);
        setSavedGraphs(newSavedGraphs);
        setLoading(false);
        lastSavedGraph.current = graphName;
        toast.success("Graph saved!");
      }).catch(err => {
        setLoading(false);
        toast.error("Failed to save graph.");
        console.error("Save graph error:", err);
      });
    }
  }

  useHotkeys("ctrl+s", saveGraph, { preventDefault: true });

  useEffect(() => {
    fetch('/dcr-js/examples/generated_examples.txt')
      .then(response => {
        if (!response.ok) {
          throw new Error('Failed to fetch examples status code: ' + response.status);
        }
        return response.text();
      })
      .then(data => {
        let files = data.split('\n');
        files.pop();
        files = files.map(name => name.split('.').slice(0, -1).join('.'));
        setExamplesData(files);
      }).catch(err => {
          console.error("Failed to load examples:", err);
          toast.error("Could not load examples.");
      });
  }, []);

  const open = (data: string, parse: ((xml: string) => Promise<void>) | undefined, importFn?: string) => {
    const importName = importFn?.slice(0, -4);
    setLoading(true);
    parse && parse(data).then(_ => {
        setGraphName(importName ? importName : initGraphName);
        setGraphId(importName ? importName : "");
        toast.success(`Graph '${importName || 'New Diagram'}' loaded.`);
    }).catch((e) => {
        console.error("Error parsing XML:", e);
        toast.error("Unable to parse or load XML.");
    }).finally(() => {
        setLoading(false);
    });
  }

  const saveAsXML = async () => {
    if (!modelerRef.current) {
        toast.error("Modeler not available.");
        return;
    }
    try {
        const data = await modelerRef.current.saveXML({ format: true });
        const blob = new Blob([data.xml], { type: 'application/xml;charset=utf-8' });
        saveAs(blob, `${graphName}.xml`);
    } catch (err) {
        toast.error("Failed to save graph as XML.");
        console.error("saveAsXML error:", err);
    }
  }

  const saveAsDCRXML = async () => {
    if (!modelerRef.current) {
        toast.error("Modeler not available.");
        return;
    }
    try {
        const data = await modelerRef.current.saveDCRXML();
        const blob = new Blob([data.xml], { type: 'application/xml;charset=utf-8' });
        saveAs(blob, `${graphName}.xml`);
    } catch (err) {
        toast.error("Failed to save graph as DCR Solutions XML.");
        console.error("saveAsDCRXML error:", err);
    }
  }

  const saveAsSvg = async () => {
    if (!modelerRef.current) {
        toast.error("Modeler not available.");
        return;
    }
    try {
        const data = await modelerRef.current.saveSVG();
        const blob = new Blob([data.svg], { type: 'image/svg+xml;charset=utf-8' });
        saveAs(blob, `${graphName}.svg`);
    } catch (err) {
        toast.error("Failed to save graph as SVG.");
        console.error("saveAsSvg error:", err);
    }
  }

  const savedGraphElements = () => {
    return Object.keys(savedGraphs).length > 0 ? [{
      text: "Saved Graphs:",
      elements: Object.keys(savedGraphs).map(name => {
        return ({
          icon: <BiLeftArrowCircle />,
          text: name,
          onClick: () => { open(savedGraphs[name], modelerRef.current?.importXML, name + ".xml"); setMenuOpen(false) },
        })
      })
    }] : [];
  }

  const menuElements: Array<ModalMenuElement> = [
    {
      icon: <BiPlus />,
      text: "New Diagram",
      onClick: () => { open(emptyBoardXML, modelerRef.current?.importXML, "New Diagram.xml"); setMenuOpen(false) },
    },
    {
      icon: <BiSave />,
      text: "Save Graph",
      onClick: () => { saveGraph(); setMenuOpen(false) },
    },
    {
      text: "Open",
      elements: [
        {
          customElement: (
            <StyledFileUpload>
              <FileUpload accept="text/xml" fileCallback={(fileName, contents) => { open(contents, modelerRef.current?.importXML, fileName); setMenuOpen(false); }}>
                <div />
                <>Open Editor XML</>
              </FileUpload>
            </StyledFileUpload>),
        },
        {
          customElement: (
            <StyledFileUpload>
              <FileUpload accept="text/xml" fileCallback={(fileName, contents) => { open(contents, modelerRef.current?.importDCRPortalXML, fileName); setMenuOpen(false); }}>
                <div />
                <>Open DCR Solution XML</>
              </FileUpload>
            </StyledFileUpload>),
        },
        {
          customElement: (
            <StyledFileUpload>
              <FileUpload accept="text/xml,.bpmn" fileCallback={async (uploadedFileName, contents) => {
                setMenuOpen(false);
                setLoading(true);
                try {
                  const dcrXmlOrError = await convertBPMNToDCRWithPyodide(contents);

                  if (dcrXmlOrError.startsWith("PYTHON_") || dcrXmlOrError.startsWith("PYODIDE_")) {
                    const { title, message } = handleConversionError(dcrXmlOrError);
                    toast.error(title + (message ? `\n\n${message}` : ''), { autoClose: 15000, style: { whiteSpace: 'pre-line' } });
                  } else {
                    // Success: dcrXmlOrError is actual DCR XML
                    const dcrXml = dcrXmlOrError;
                    if (modelerRef.current?.importDCRPortalXML) {
                      await modelerRef.current.importDCRPortalXML(dcrXml);
                      const newGraphName = uploadedFileName.replace(/\.(bpmn|xml)$/i, '');
                      setGraphName(newGraphName);
                      setGraphId(""); // Imported graph is not yet saved with this name
                      
                      toast.info("BPMN model converted. Attempting to apply automatic layout and nesting...");

                      const elementRegistry = modelerRef.current?.getElementRegistry();
                      if (elementRegistry) {
                        const events = Object.values(elementRegistry._elements)
                          .filter((element: any) => element.element.id.includes("Event") && !element.element.id.includes("SubProcess")); // Exclude sub-processes from this check
                        const uniqueActivities = new Set(events.map((element: any) => element.element.businessObject.description ? element.element.businessObject.description.trim() : ""));
                        
                        // Check for empty strings and if the number of unique non-empty descriptions matches the number of events
                        const hasEmptyDescriptions = uniqueActivities.has("");
                        const uniqueNonEmptyActivitiesCount = uniqueActivities.delete("") ? uniqueActivities.size : uniqueActivities.size; // .delete returns boolean

                        if (events.length === uniqueNonEmptyActivitiesCount && !hasEmptyDescriptions) {
                          try {
                            const graph = moddleToDCR(elementRegistry, true);
                            const nestings = nestDCR(graph);
                            const params: [DCRGraph, Nestings] = [nestings.nestedGraph, nestings];
                            
                            const nestedXml = await layoutGraph(...params);
                            await modelerRef.current.importXML(nestedXml); // Re-import with layout
                            
                            toast.success("BPMN successfully converted, laid out, and nested!");
                          } catch (nestError) {
                            console.error("Error nesting/layout graph:", nestError);
                            toast.warning("BPMN converted but automatic layout/nesting failed. The graph is loaded without optimal layout.");
                          }
                        } else {
                          toast.warning("BPMN converted. Automatic layout/nesting skipped due to DCR events having empty or duplicate activity names (descriptions). Please review event labels. The graph is loaded without optimal layout.");
                        }
                      } else {
                        toast.success("BPMN successfully converted to DCR!"); // No element registry for layout
                      }
                    } else {
                        toast.error("DCR Modeler is not available to import the converted graph.");
                    }
                  }
                } catch (error) { 
                  // This catch is for errors during the await convertBPMNToDCRWithPyodide() itself (e.g., Pyodide script failed to load)
                  // or other unexpected JS errors in this try block.
                  console.error("Critical error during BPMN conversion process:", error);
                  let displayTitle = "Conversion Process Error";
                  let displayMessage = "An unexpected critical error occurred.";

                  if (error instanceof Error) {
                    displayMessage = error.message;
                     if (error.message.toLowerCase().includes("failed to fetch") || error.message.toLowerCase().includes("network error")) {
                        displayTitle = "Network or Resource Error";
                        displayMessage = `Could not load necessary resources (e.g., Pyodide). Please check your internet connection. Details: ${error.message}`;
                    } else if ((error as any).name === 'PythonError') { // Check if it's a PythonError that wasn't caught and returned as string
                        displayTitle = "Critical Python Execution Error";
                        displayMessage = `Details: ${(error as any).message}. Check console for full Python traceback.`;
                    }
                  } else if (typeof error === 'string') {
                    displayMessage = error; // Should be rare here, as convertBPMNToDCRWithPyodide returns strings for Python errors
                  }
                  toast.error(`${displayTitle}\n\n${displayMessage}`, { autoClose: 20000, style: { whiteSpace: 'pre-line' } });
                } finally {
                  setLoading(false);
                }
              }}>
                <div />
                <>Open BPMN 2.0 XML</>
              </FileUpload>
            </StyledFileUpload>),
        },
      ]
    },
    {
      text: "Download",
      elements: [{
        icon: <div />,
        text: "Download Editor XML",
        onClick: () => { saveAsXML(); setMenuOpen(false) },
      },
      {
        icon: <div />,
        text: "Download DCR Solutions XML",
        onClick: () => { saveAsDCRXML(); setMenuOpen(false) },
      },
      {
        icon: <div />,
        text: "Download SVG",
        onClick: () => { saveAsSvg(); setMenuOpen(false) },
      }
      ],
    },
    {
      icon: <BiSolidDashboard />,
      text: "Examples",
      onClick: () => { setMenuOpen(false); setExamplesOpen(true) },
    },
    ...savedGraphElements()
  ]

  const bottomElements: Array<ModalMenuElement> = [
    {
      customElement:
        <MenuElement>
          <Toggle initChecked={true} onChange={(e) => modelerRef.current?.setSetting("blackRelations", !e.target.checked)} />
          <Label>Coloured Relations</Label>
        </MenuElement>
    },
    {
      customElement:
        <MenuElement>
          <DropDown
            options={[{ title: "TAL2023", value: "TAL2023", tooltip: "https://link.springer.com/chapter/10.1007/978-3-031-46846-9_12" }, { title: "HM2011", value: "HM2011", tooltip: "https://arxiv.org/abs/1110.4161" }, { title: "DCR Solutions", value: "DCR Solutions", tooltip: "https://dcrsolutions.net/" }]}
            onChange={(option) => isSettingsVal(option) && modelerRef.current?.setSetting("markerNotation", option)}
          />
          <Label>Relation Notation</Label>
        </MenuElement>
    }
  ]

  const initXml = lastGraph ? savedGraphs[lastGraph] : undefined;

  const layout = () => {
    if (!modelerRef.current) {
        toast.warn("Modeler not available for layout.");
        return;
    }
    setLoading(true); 
    const elementRegistry = modelerRef.current?.getElementRegistry();
    if (!elementRegistry) {
        toast.error("Element registry not available for layout.");
        setLoading(false);
        return;
    }
    const events = Object.values(elementRegistry._elements).filter((element: any) => element.element.id.includes("Event") && !element.element.id.includes("SubProcess"));
    const uniqueActivities = new Set(events.map((element: any) => element.element.businessObject.description ? element.element.businessObject.description.trim() : ""));
    
    const hasEmptyDescriptions = uniqueActivities.has("");
    uniqueActivities.delete(""); // remove empty string for count if it exists
    const uniqueNonEmptyActivitiesCount = uniqueActivities.size;


    if (events.length !== uniqueNonEmptyActivitiesCount || hasEmptyDescriptions) {
      toast.warning("Automatic layout skipped: DCR events must have unique, non-empty activity names (descriptions).", {autoClose: 10000});
      setLoading(false);
      return;
    }
    if (Object.values(elementRegistry._elements).some((element: any) => 
        element.element.id.includes("SubProcess") || (element.element.businessObject && element.element.businessObject.role)
    )) {
      toast.warning("Automatic layout skipped: Graph contains subprocesses or roles, which are not supported by this layout function.", {autoClose: 10000});
      setLoading(false);
      return;
    }

    if (confirm("This will overwrite your current layout. Do you wish to continue?")) {
      try {
        const nest = confirm("Do you wish to attempt automatic nesting as part of the layout (recommended for structured graphs)?");
        const graph = moddleToDCR(elementRegistry, true); 
        const nestings = nestDCR(graph);
        const params: [DCRGraph, Nestings | undefined] = nest ? [nestings.nestedGraph, nestings] : [graph, undefined];
        
        layoutGraph(...params).then(xml => {
          modelerRef.current?.importXML(xml).then(() => {
            toast.success(nest ? "Graph automatically laid out and nested!" : "Graph automatically laid out!");
          }).catch(e => {
            console.error("Error importing XML from layout service:", e);
            toast.error("Invalid XML returned from layout service.")
          }).finally(() => {
            setLoading(false);
          });
        }).catch(e => {
          console.error("Error from layoutGraph service:", e);
          toast.error("Unable to layout graph using the service.");
          setLoading(false);
        });
      } catch (e) {
        console.error("Error during layout preparation:", e);
        toast.error("An unexpected error occurred during layout preparation.");
        setLoading(false);
      }
    } else {
        setLoading(false); 
    }
  }

  return (
    <>
      <GraphNameInput
        value={graphName}
        onChange={e => setGraphName(e.target.value)}
      />
      {loading && <Loading />}
      <Modeler initXml={initXml} modelerRef={modelerRef} />
      <TopRightIcons>
        <BiAnalyse title="Layout Graph" onClick={layout} />
        <FullScreenIcon />
        <BiHome onClick={() => setState(StateEnum.Home)} />
        <ModalMenu elements={menuElements} bottomElements={bottomElements} open={menuOpen} setOpen={setMenuOpen} />
      </TopRightIcons>
      {examplesOpen && <Examples
        examplesData={examplesData}
        openCustomXML={(xml) => open(xml, modelerRef.current?.importCustomXML, "Custom Example.xml")}
        openDCRXML={(xml) => open(xml, modelerRef.current?.importDCRPortalXML, "DCR Example.xml")}
        setExamplesOpen={setExamplesOpen}
        setLoading={setLoading}
      />}
    </>
  )
}

export default ModelerState;